name: news_app_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  built_value: ^8.9.2
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  built_value_generator: ^8.9.2
  retrofit_generator: ^8.1.2
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4

flutter:
  uses-material-design: true
